version: '3.8'

services:
  auth-service:
    container_name: auth_service
    build: ./
    ports:
      - "8083:8083"
    networks:
      - global
    depends_on:
      - postgres-db
    dns:
      - 8.8.8.8
      - 8.8.4.4

  migrate:
    image: migrate/migrate
    networks:
      - global
    volumes:
      - ./internal/migration:/migration
    command: [ "-path", "/migration", "-database",
               "postgres://postgres:1234@user-service:5432/cinemauserservice?sslmode=disable",
               "up" ]
    depends_on:
      - postgres-db

  postgres-db:
    container_name: user-service
    image: postgres:latest
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: cinemauserservice
    volumes:
      - db:/post-database/post-memory
    ports:
      - "5431:5432"
    networks:
      - global
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  global:
    external: true
    name: cinema
    driver: bridge


volumes:
  db:
